### PR TITLE
Add Emoji 14.0

### PR DESCRIPTION
**Pull request by MarcoMahone721**
Can you please release Emoji 14.0 on Saturday? Are are you done with them yet?

### CODE REVIEW

**Comment by DeeDeeG** [comment]
It looks like this comment was meant for user C1710 regarding their fork... That fork has released an Emoji 14.0 version... And this PR has not much relevance to the actual repo it got opened in. I think this can be closed?

**Comment by rsheeter** [comment]
I can't publicly commit to a date for Unicode 14. I think it's safe to say I expect it will come :)

**Comment by twardoch** [comment]
The readiness is all.

**Comment by MarcoMahone721** [comment]
That's okay because C1710 already added emoji 14.0 into blobmoji. And this request in here was a accident.

**Pull request closed without merging**
