### PR TITLE
Rebuild all waved SVG flags with latest picosvg and rsheeter/warp tool

### PR DESCRIPTION
**Pull request by anthrotype**
Fixes https://github.com/googlefonts/color-fonts/issues/86 among others

(I wish github had a built-in SVG diff viewer)

### CODE REVIEW

**Comment by dscorbett** [comment]
GitHub does have a built-in SVG diff viewer. By default, it shows the diff as plain text, but you can click the page icon (“Display the rich diff”) on the right side of the file’s diff box header to get a visual diff.

**Comment by anthrotype** [comment]
Amazing, thanks David! I thought I had seen that before, but had forgotten how to activate :)

**Comment by anthrotype** [comment]
hm looking at the diffs, I think I've spotted another picosvg bug related to inherited stroke attributes (will file a bug upstream and try to fix before coming back to this)

**Review by rsheeter — APPROVED** [review]

**Comment by anthrotype** [comment]
After applying https://github.com/googlefonts/picosvg/issues/257 and https://github.com/googlefonts/picosvg/pull/259, the newly waved flags all look good now

**Review by rsheeter — APPROVED** [review]

**Comment by rsheeter** [comment]
> the newly waved flags all look good now

Nice! We should push a build of picosvg and update color-fonts; my demo flags look a bit wonky in a few places :)

**Pull request merged**
