### PR TITLE
Updated all versions of Martinique flag

### PR DESCRIPTION
**Pull request by chrism**
The current version of the Martinique Flag is outdated

MQ

This PR updates it to the correct version for all formats (html/png/svg/waved-svg)

MQ

### CODE REVIEW

**Comment by anthrotype** [comment]
Thanks. Can you please confirm where the assets come from or how they were generated?
Did you use https://github.com/fonttools/region-flags to download the flag from wikipedia and convert to optimized PNG?
And did you use https://github.com/rsheeter/warp to make the "waved" svg version?

I noticed that https://github.com/googlefonts/noto-emoji/tree/main/third_party/region-flags contains a REDME that mentions a bunch of scripts which aren't there any more, maybe we should update the instructions. /cc @rsheeter @behdad

**Comment by chrism** [comment]
Hi @anthrotype, sure thing.

> Did you use https://github.com/fonttools/region-flags to download the flag from wikipedia and convert to optimized PNG?

Yes

> And did you use https://github.com/rsheeter/warp to make the "waved" svg version?

Yes

> I noticed that https://github.com/googlefonts/noto-emoji/tree/main/third_party/region-flags contains a REDME that mentions a bunch of scripts which aren't there any more, maybe we should update the instructions. /cc @rsheeter @behdad

tbh there were a few confusing aspects to the process.

Like you say, the scripts referred to in the googlefonts README do not exist, but I found them via this issue
https://github.com/googlefonts/noto-emoji/issues/164

The process to generate the waved svg is not included in the https://github.com/fonttools/region-flags repo but I found it via this issue
https://github.com/googlefonts/noto-emoji/issues/3

**Review by anthrotype — APPROVED** [review]

**Comment by rsheeter** [comment]
Thank you for the PR. I looked into this and our flags policy has evolved to require the asset come from the relevant government (admittedly contrary to the current documentation of region flags) so I do not believe I can merge this. I will update the font to include an updated flag.

**Comment by rsheeter** [comment]
I should add that I really appreciate the effort and apologize for not being able to accept the PR

**Comment by rsheeter** [comment]
Update in https://github.com/googlefonts/noto-emoji/pull/448

**Comment by chrism** [comment]
Hi @rsheeter no problem, just happy to see the flag has been changed. Thanks for the update.

**Pull request closed without merging**
