### PR TITLE
Region flags change.

### PR DESCRIPTION
**Pull request by qqd-google**
Add flags for
BL: Saint Barthélemy
BQ: Caribbean Netherlands
MQ: Martinique
RE: Réunion
TF: French Southern Territories

Change flag for
XK: Kosovo

### CODE REVIEW

**Comment by qqd-google** [comment]
This fixed the region flag. Please abandon last region flag cl. Thanks!

Sorry about it.

**Comment by ZanderBrown** [comment]
Hey it's that random guy again:

Acording to [ISO 3166-1](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#BL) BQ represents the whole of the "Caribbean Netherlands" which has no specific flag thus should be aliased to NL

Similarly RE is a proposed design so should probably stay aliased to FR (that said some buildings use it apparently)


Wikipedia seems to suggest MQ is
image not 
image so I'm not sure what's happening there

**Comment by qqd-google** [comment]
Basically I got the idea of which flags should be used for which regions from designers. 
I'll double check and let our pm and designers know about this. Thanks!

What I found:
https://en.wikipedia.org/wiki/File:Flag_of_Bonaire.svg
https://en.wikipedia.org/wiki/Flag_of_Martinique

**Comment by dougfelt** [comment]
Which flags get used for a region is a controversial topic and requires input from geo. I assume the PM is the one to ensure this has all been vetted.

**Comment by ZanderBrown** [comment]
> https://en.wikipedia.org/wiki/Flag_of_Martinique

Ah! That explains where the flag came from, final sentence is concerning though:

> Usage is controversial, because of its historical origin: upon adoption, the "Snake flag" flag fluttered on ships engaged in triangular trade—and thus the Atlantic slave trade. 

So it seems far safer to use the [recently adopted](http://vexillologynews.com/martinique-new-flag/) official flag

For BQ though it represents the whole of "Bonaire, Sint Eustatius and Saba" not just "Bonaire" so whilst I don't know the local politics I imagine "Sint Eustatius and Saba" would object to the flag appying to all of them (perhaps we need regional variants for all 3?)

Flags are an incredibly tricky issue, surprised GB-NIR hasn't caused problems :-)

**Comment by sg3510** [comment]
Thanks for raising this. Currently all vendors use the snake flag for MQ (https://emojipedia.org/flag-for-martinique/) so will be kept for consistency this release. However we can consider changing next year as we understand the adoption of the new flag.

This is a similar reasoning to the BQ flag (https://emojipedia.org/flag-for-caribbean-netherlands/)

**Comment by ZanderBrown** [comment]
Yes using NL to represent BQ seems the safest option, but this MR changes it

**Comment by DeeUnderscore** [comment]
Was this supposed to correct FR.svg? Becuase it [still appears to be the flag of the French Southern and Antarctic Lands](https://github.com/googlefonts/noto-emoji/blob/51b61919fbed90be4e1ad430f44d2587383e092b/third_party/region-flags/svg/FR.svg) on master...

**Pull request merged**
