### PR TITLE
Revert the PILE OF POO (1f4a9) emoji to its previous (non-anthropomorphic) version

### PR DESCRIPTION
**Pull request by paradox460**
This PR reverts the PILE OF POO emoji to its non-anthropomorphic version. The previous version had its own unique character, while still conveying the same meaning as other platforms

### CODE REVIEW

**Comment by Rican7** [comment]
:+1:

**Comment by Jasperswaagman** [comment]
+1

**Comment by waldyrious** [comment]
:+1:, much better IMO.

**Comment by FiveYellowMice** [comment]
+1

**Comment by kokesh** [comment]
We want the old shit back!

**Comment by JulianNorton** [comment]
:hankey:

**Comment by xiangyexiao** [comment]
The new design of the poo is intended to be anthropomorphic but we will take in feedback to improve the design in the future.

**Comment by dougfelt** [comment]
Obviously, it's anthroopoomorphic...

**Comment by Ugion** [comment]
:+1:

**Comment by blokhut** [comment]
+1

**Comment by rakiru** [comment]
+1

**Comment by dougfelt** [comment]
Obviously Unicode needs to define a variation selector for the poo emoji - with/without flies, with/without eyes and smiley face... :-/

**Comment by paradox460** [comment]
ZWJ joiners for poos

**Comment by dougfelt** [comment]
Just makes a bigger pile of poo...

**Comment by Jop-V** [comment]
Yeah! New ZWJ joiner: `💩🐜👀`

😸

**Comment by sg3510** [comment]
💩💩💩
Closing since we are no longer using this design.

**Pull request closed without merging**
