### PR TITLE
Region flags change.

### PR DESCRIPTION
**Pull request by qqd-google**
Add flags for
BL: Saint Barthélemy
BQ: Caribbean Netherlands
MQ: Martinique
RE: Réunion
TF: French Southern Territories

Change flag for
XK: Kosovo

### CODE REVIEW

**Comment by qqd-google** [comment]
Please review this CL and merge it. 
Thanks!

**Comment by dougfelt** [comment]
So we've always sourced from the data in github/behdad/region-flags, because this ensured the data was in the public domain.  This request seems to have a new version of the FR.svg flag which hasn't changed in the upstream repo for many years, so I'm wondering where it comes from.

**Comment by qqd-google** [comment]
Thank you for checking it! I'll send another CL to fix this mistake in next CL.
And rest assured, the font file I generated for Android a while ago is correct, without this mistake.
Here is what happened. 
1. I download new flags svg/png files from wikipedia for the 6 regions, and put them in region_flag/svg and region_flag/png folders. I forgot how I put them into the folder. But the French and Netherlands flags are untouched. So the font was correctly generated. (Just checked a moment ago)
2. Today when I wanted to submit the region_flags related content, I started a new branch from master, and then copied png and svg files to region_flag/svg and region_flag/png folders. Then the weird thing happened.
3. I checked, on original master branch, BL.png, TF.png, and BQ.png are "Link to Image" type, and BL and TF link to FR.png, and BQ link to NL.png. When I copied them, somehow the FR.png and NL.png are modified.

**Comment by qqd-google** [comment]
OK. I think it's better to revoke this CL. Then I'll upload a new CL. Thanks!

**Comment by ZanderBrown** [comment]
Was about the report this!

We where passing through (interesting discussion on unicode flag representation was occurring) and we were intrigued by the latest commit being within hours, only to see it contained an obvious mistake!

Glad to see it's an honest mistake not some great conspiracy :-)

**Comment by dougfelt** [comment]
I think still the place to get region flags is from behdad/region-flags on github.  I believe he (or someone) still maintains it, you might ping him as I don't think the data has changed for a few years.  Anyway, they went through the effort to make sure all the flag data was available under the right licensing terms.  It wasn't the case many years ago (maybe this is changed) that flag images uploaded and used in wikipedia are always available under terms we can use.

In our flag data when a region uses another country's flag I believe we store soft links rather than copies of the flag image data, and the emoji build process resolves these.  I didn't check to see if any of the added region flags are in this situation.

**Comment by qqd-google** [comment]
Some of the newly added flags used to link to another flag, but now they use their own flags.
I just checked behdad/region-flags, and saw the new flags are not updated. For example, BL, BQ, TF are still linked to FR and NL.
Just sent him an email.

**Pull request merged**
